# Generated by Django 3.1 on 2022-03-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workertypework',
            name='time',
        ),
    ]
