# Generated by Django 3.1 on 2022-03-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=50, verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'TipoTrabajo',
                'verbose_name_plural': 'TiposTrabajos',
                'db_table': 'tipoTrabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nameworker', models.CharField(max_length=150, verbose_name='Nombre')),
                ('address', models.CharField(max_length=150, verbose_name='Direccion')),
                ('curp', models.CharField(max_length=20, verbose_name='CURP')),
                ('email', models.CharField(max_length=50, verbose_name='Correo')),
                ('age', models.IntegerField(default=0)),
                ('typeWorker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.work')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'trabajador',
                'ordering': ['id'],
            },
        ),
    ]
