# Generated by Django 3.1 on 2022-03-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('attackname', models.CharField(max_length=100, verbose_name='Nombre')),
                ('levelattack', models.IntegerField(default=0, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Ataque',
                'verbose_name_plural': 'Ataques',
                'db_table': 'ataque',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('leveltype', models.IntegerField(default=0, verbose_name='Nivel')),
                ('typename', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('namepokemon', models.CharField(max_length=100, verbose_name='Nombre')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenadorPokemon.attack')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenadorPokemon.type')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
                'db_table': 'pokemon',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='coachPokemon',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('namecoach', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('age', models.IntegerField(default=0, verbose_name='Edad')),
                ('email', models.CharField(max_length=50, verbose_name='Correo')),
                ('password', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('initialPokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenadorPokemon.pokemon')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'db_table': 'entrenador',
                'ordering': ['id'],
            },
        ),
    ]
