# Generated by Django 3.1 on 2022-03-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadorPokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachpokemon',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
